namespace AIntern.Core.Models;

/// <summary>
/// Defines the role of a participant in a chat conversation.
/// </summary>
/// <remarks>
/// The role determines how the message is displayed in the UI
/// and how the LLM interprets the message in the prompt context.
/// </remarks>
public enum MessageRole
{
    /// <summary>
    /// A system message that provides instructions or context to the model.
    /// Typically used for setting the assistant's behavior or persona.
    /// </summary>
    System,

    /// <summary>
    /// A message from the human user.
    /// These form the input that the model responds to.
    /// </summary>
    User,

    /// <summary>
    /// A response generated by the AI assistant.
    /// These messages are produced by the LLM during inference.
    /// </summary>
    Assistant
}

/// <summary>
/// Represents a single message in a chat conversation.
/// Contains the message content, metadata, and optional generation statistics.
/// </summary>
/// <remarks>
/// Messages are immutable once created, except for Content (which updates during streaming)
/// and the completion/statistics fields.
/// </remarks>
public sealed class ChatMessage
{
    /// <summary>
    /// Gets the unique identifier for this message.
    /// Auto-generated on creation.
    /// </summary>
    public Guid Id { get; init; } = Guid.NewGuid();

    /// <summary>
    /// Gets the role of the message sender (System, User, or Assistant).
    /// Determines display styling and prompt formatting.
    /// </summary>
    public MessageRole Role { get; init; }

    /// <summary>
    /// Gets or sets the text content of the message.
    /// Mutable to allow incremental updates during streaming.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Gets the UTC timestamp when this message was created.
    /// Used for conversation ordering and display.
    /// </summary>
    public DateTime Timestamp { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Gets or sets whether the message generation is complete.
    /// False during streaming, True once the response is finished.
    /// </summary>
    public bool IsComplete { get; set; } = true;

    /// <summary>
    /// Gets or sets the number of tokens in this message, if known.
    /// Useful for context window management and cost estimation.
    /// </summary>
    public int? TokenCount { get; set; }

    /// <summary>
    /// Gets or sets the time taken to generate this message, if applicable.
    /// Only populated for Assistant messages after generation completes.
    /// </summary>
    public TimeSpan? GenerationTime { get; set; }

    /// <summary>
    /// Gets or sets the sequence number for ordering within a conversation.
    /// Assigned automatically when adding messages to a conversation.
    /// </summary>
    /// <remarks>
    /// Used for database storage and ensuring consistent message ordering.
    /// Starts at 1 for the first message in a conversation.
    /// </remarks>
    public int SequenceNumber { get; set; }
}
