namespace AIntern.Core.Models;

using AIntern.Core.Enums;

/// <summary>
/// Represents a single result from a full-text search operation.
/// </summary>
/// <remarks>
/// <para>
/// This record encapsulates all data needed to display and navigate to a search result:
/// </para>
/// <list type="bullet">
///   <item><description><b>Identity:</b> Id, ResultType, ConversationId, MessageId</description></item>
///   <item><description><b>Display:</b> Title, Preview (highlighted snippet)</description></item>
///   <item><description><b>Relevance:</b> Rank (BM25 score from FTS5)</description></item>
///   <item><description><b>Context:</b> Timestamp for display and sorting</description></item>
/// </list>
/// <para>
/// <b>FTS5 Ranking:</b> The Rank property contains the BM25 score from SQLite FTS5.
/// Lower (more negative) values indicate better matches. Typical values range from
/// -10 (excellent match) to 0 (poor match).
/// </para>
/// <para>
/// <b>Preview Generation:</b> For message results, the Preview contains a snippet
/// generated by FTS5's snippet() function with matched terms highlighted using
/// &lt;mark&gt; tags. For conversation results, the Preview is the full title.
/// </para>
/// <para>Added in v0.2.5a.</para>
/// </remarks>
/// <param name="Id">Unique identifier for this search result (for UI binding).</param>
/// <param name="ResultType">Whether this result matches a conversation or message.</param>
/// <param name="Title">Display title (conversation title or parent conversation title for messages).</param>
/// <param name="Preview">Snippet of matched content with search terms highlighted.</param>
/// <param name="Rank">FTS5 BM25 relevance score (lower is better).</param>
/// <param name="Timestamp">When the matched entity was last updated.</param>
/// <param name="ConversationId">The conversation ID (always set).</param>
/// <param name="MessageId">The message ID (null for Conversation results).</param>
/// <example>
/// Creating a search result for a conversation match:
/// <code>
/// var result = new SearchResult(
///     Id: Guid.NewGuid(),
///     ResultType: SearchResultType.Conversation,
///     Title: "Project Planning Discussion",
///     Preview: "Project Planning Discussion",
///     Rank: -5.2,
///     Timestamp: DateTime.UtcNow,
///     ConversationId: conversationId,
///     MessageId: null);
/// </code>
/// </example>
public sealed record SearchResult(
    Guid Id,
    SearchResultType ResultType,
    string Title,
    string Preview,
    double Rank,
    DateTime Timestamp,
    Guid ConversationId,
    Guid? MessageId)
{
    #region Computed Properties

    /// <summary>
    /// Gets a value indicating whether this result is a conversation match.
    /// </summary>
    /// <value>True if <see cref="ResultType"/> is <see cref="SearchResultType.Conversation"/>.</value>
    /// <remarks>
    /// Convenience property for UI binding and filtering.
    /// </remarks>
    public bool IsConversationResult => ResultType == SearchResultType.Conversation;

    /// <summary>
    /// Gets a value indicating whether this result is a message match.
    /// </summary>
    /// <value>True if <see cref="ResultType"/> is <see cref="SearchResultType.Message"/>.</value>
    /// <remarks>
    /// Convenience property for UI binding and filtering.
    /// </remarks>
    public bool IsMessageResult => ResultType == SearchResultType.Message;

    /// <summary>
    /// Gets a human-readable type label for display.
    /// </summary>
    /// <value>"Conversation" or "Message" based on <see cref="ResultType"/>.</value>
    /// <remarks>
    /// Used for displaying result type badges in the search results UI.
    /// </remarks>
    public string TypeLabel => ResultType switch
    {
        SearchResultType.Conversation => "Conversation",
        SearchResultType.Message => "Message",
        _ => "Unknown"
    };

    /// <summary>
    /// Gets a formatted relevance score for display.
    /// </summary>
    /// <value>
    /// The BM25 rank formatted to 2 decimal places.
    /// </value>
    /// <remarks>
    /// <para>
    /// BM25 scores are negative, with more negative values indicating better matches.
    /// </para>
    /// <list type="bullet">
    ///   <item><description><b>-10.0 to -5.0:</b> Excellent match</description></item>
    ///   <item><description><b>-5.0 to -2.0:</b> Good match</description></item>
    ///   <item><description><b>-2.0 to 0.0:</b> Fair match</description></item>
    /// </list>
    /// </remarks>
    public string FormattedRank => Rank.ToString("F2");

    /// <summary>
    /// Gets the timestamp formatted for display.
    /// </summary>
    /// <value>
    /// The timestamp formatted as a short date and time string.
    /// </value>
    public string FormattedTimestamp => Timestamp.ToString("g");

    #endregion
}
